### ISSUE TITLE
Reports are not working with curent AWS api

### ISSUE THREAD

**Issue by hiteshj** [TheLordBaski/Amazon-mws-nodejs-sdk#4]
Hello Dear,

Please check your reports services which is not working and throwing error below:

<ErrorResponse xmlns="https://mws.amazonservices.com/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidAddress</Code>
    <Message>Invalid Section name or version provided - 2009-01-01/2009-01-01</Message>
  </Error>
  <RequestID>2ce68b8a-4fc6-4371-9ce4-bcff8e37ba7b</RequestID>
</ErrorResponse>

**Comment by hiteshj** [comment]
If i change the path path: 'endpoint[params.type].type + endpoint[params.type].version + "?" + body'  TO 'path: endpoint[params.type].type + "?" + body'

Then error is : SignatureDoesNotMatch

**Comment by TheLordBaski** [comment]
I will look at it soon. My pc crashed today so I need to reinstall everything.

But thanks for report.

**Comment by TheLordBaski** [comment]
Hi @hiteshj ,
sorry for late reply. 
Can you give me whole path of request ?

**Comment by jvgeee** [comment]
@hiteshj  @TheLordBaski Any update on this?

**Comment by jvgeee** [comment]
@TheLordBaski I'm getting the same error, ym path is:

```
mws.reports.RequestReport(config, { ReportType: '_GET_FLAT_FILE_OPEN_LISTINGS_DATA_'}, function(err, data){
          if(err){
            console.log(err);
            res.status(500).send(err);
          }else{
            console.log(data);
          }
        })
```

My response is:

```
{ xmlns: 'https://mws.amazonservices.com/',
  Error: 
   { Type: 'Sender',
     Code: 'InvalidAddress',
     Message: 'Invalid Section name or version provided - 2009-01-01/2009-01-01' },
  RequestID: '6ce58f91-69c7-4a4f-ad09-d0a49b44ad90' }

```

**Comment by jvgeee** [comment]
Ok, I fixed it. The solution is to change `mws.js` line 16 to:

`var url = "mws.amazonservices.com";`

Then, from line 34:

```
'Reports': {
        'type': '/Reports/',
        'version': '2009-01-01'
    }
```

**Comment by TheLordBaski** [comment]
Hi man,
I can' update and test this because I have no mws tokens . I can left you
whole repo if you want :)

S pozdravem / Best regards,

_Bc. Jakub GabčoNodeJS *
*vývojář / NodeJS
developer------------------------------------------------------------------------------_
Tel.:     +421 918 776 982 <%2B420%C2%A0734%C2%A0622%20430>

## Email:  _jakub.gabco__@ki-wi.cz oldrich.esner@ki-wi.cz_

_Ki-Wi Digital s.r.o._
Lidická 27, 602 00 Brno
Czech Republic
www.ki-wi.cz

2016-02-04 19:12 GMT+01:00 jascination notifications@github.com:
